version: '3.8'

services:
  db:
    image: postgres:16
    container_name: sinalize_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sinalizepwd
      POSTGRES_DB: sinalize
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
