CREATE TABLE palavras (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  palavra VARCHAR(255),
  criado_por INT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_por INT,
  atualizado_em TIMESTAMP
);

CREATE TABLE usuarios (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255),
  email VARCHAR(255),
  senha VARCHAR(255),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categorias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255),
  descricao VARCHAR(400),
  criado_por INT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  atualizado_por INT,
  atualizado_em TIMESTAMP
);

CREATE TABLE palavras_categorias (
  id_palavra INT,
  id_categoria INT,
  PRIMARY KEY (id_palavra, id_categoria)
);

-- Chaves Estrangeiras (Foreign Keys)
ALTER TABLE palavras_categorias ADD FOREIGN KEY (id_palavra) REFERENCES palavras (id) ON DELETE CASCADE;
ALTER TABLE palavras_categorias ADD FOREIGN KEY (id_categoria) REFERENCES categorias (id) ON DELETE CASCADE;

ALTER TABLE categorias ADD FOREIGN KEY (criado_por) REFERENCES usuarios (id) ON DELETE RESTRICT;
ALTER TABLE categorias ADD FOREIGN KEY (atualizado_por) REFERENCES usuarios (id) ON DELETE SET NULL;

ALTER TABLE palavras ADD FOREIGN KEY (criado_por) REFERENCES usuarios (id) ON DELETE RESTRICT;
ALTER TABLE palavras ADD FOREIGN KEY (atualizado_por) REFERENCES usuarios (id) ON DELETE SET NULL;